import Head from 'next/head'
import { HeaderComponent } from '@/components/Header'
import { FormComponent } from '@/components/Form'
import { PayComponent } from '@/components/PayComponent'
import { TfiClose } from 'react-icons/tfi'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-200 w-full  min-h-screen flex items-center justify-center ' >
        <div className='bg-white w-[70%] h-[70%] flex relative ' >
          <div className='w-11 h-9 bg-gray-50 absolute top-0 right-0 flex items-center justify-center'> <TfiClose /> </div>
          <div className='w-[68%] py-8 pl-12 pr-6'>
            <HeaderComponent />
            <FormComponent />
          </div>
          <div className='flex-1 py-12 pl-6 pr-12 relative'>
            <PayComponent />
          </div>
        </div>
      </div>
    </>
  )
}
